// Real React + local network mocks. No request may leave 127.0.0.1.
import {chromium,expect} from '@playwright/test'
import {mkdir,writeFile} from 'node:fs/promises'
import {setup,school} from './browser.mjs'
const browser=await chromium.launch({channel:'chrome',headless:true})
const results=[];const base='http://127.0.0.1:3117'
async function test(name,run){const page=await browser.newPage({viewport:{width:390,height:844}});const evidence=await setup(page);try{await run(page,evidence);expect(evidence.errors).toEqual([]);results.push({name,result:'PASS'})}catch(error){results.push({name,result:'FAIL',error:error.message});console.log(name,error.message)}finally{await page.close()}}
const count=(calls,path,method='POST')=>calls.filter(x=>x.path===path&&x.method===method).length
async function intent(page,slug=school.slug,expires=Date.now()+1800000){await page.addInitScript(({slug,expires})=>sessionStorage.setItem('sl_school_candidate_v1',JSON.stringify({slug,expiresAt:expires})),{slug,expires})}
async function sharePage(page){await page.goto(base+'/account?mode=member');await page.getByRole('button',{name:'친구 불러서 학교 키우기'}).click();await expect(page.getByRole('dialog')).toBeVisible()}
try{
 await test('search: minimum, IME commit, button once',async(p,{calls})=>{
  await p.goto(base);const input=p.getByRole('combobox');await p.getByRole('button',{name:'내 학교 찾기'}).click();await expect(input).toBeFocused();expect(count(calls,'/mock/full','GET')).toBe(0)
  await input.fill('예시');await input.dispatchEvent('compositionstart');await input.press('Enter');expect(new URL(p.url()).pathname).toBe('/');expect(count(calls,'/mock/full','GET')).toBe(0)
  await input.dispatchEvent('compositionend');await p.waitForTimeout(100);await p.getByRole('button',{name:'내 학교 찾기'}).click();await expect(p.getByRole('heading',{name:/검색 결과 1건/})).toBeVisible();expect(count(calls,'/mock/full','GET')).toBe(1);await expect(p.getByRole('combobox')).toHaveValue('예시');expect(p.url()).not.toContain('예시')
 })
 await test('search: keyboard candidate and touch/click Hub',async(p,{calls})=>{await p.goto(base);const input=p.getByRole('combobox');await input.fill('예시');await expect(p.getByRole('option')).toBeVisible();await input.press('ArrowDown');await input.press('Enter');await expect(p.getByRole('heading',{name:school.school_name,exact:true})).toBeVisible();expect(count(calls,'/mock/full','GET')).toBe(0);await p.goto(base);await p.getByRole('combobox').fill('예시');await p.getByRole('option').click();await expect(p.getByRole('heading',{name:school.school_name,exact:true})).toBeVisible()})
 await test('search: blocked storage uses same-tab fallback',async(p)=>{await p.addInitScript(()=>Object.defineProperty(window,'sessionStorage',{get(){throw Error('blocked')}}));await p.goto(base);await p.getByRole('combobox').fill('예시');await p.getByRole('button',{name:'내 학교 찾기'}).click();await expect(p.getByRole('heading',{name:/검색 결과 1건/})).toBeVisible()})
 await test('search: error retry, zero result, changed input',async(p)=>{let failed=true;await p.route('**/mock/full?*',r=>r.fulfill({status:failed?503:200,contentType:'application/json',body:failed?'{}':'[]'}));await p.goto(base+'/search');await p.getByRole('combobox').fill('없는학교');await p.getByRole('button',{name:'학교 검색',exact:true}).click();await expect(p.getByText('지금은 검색 결과를 불러올 수 없어요.')).toBeVisible();failed=false;await p.getByRole('button',{name:'다시 시도'}).click();await expect(p.getByText(/검색 결과가 없어요/)).toBeVisible();await expect(p.getByRole('combobox')).toHaveValue('없는학교')})
 await test('journey: input → Hub → mock login return → confirm → save → my school → preview',async(p,{calls})=>{
  await p.goto(base);await p.getByRole('combobox').fill('예시');await p.getByRole('button',{name:'내 학교 찾기'}).click();await p.getByRole('link',{name:/예시푸른고등학교/}).click();await p.getByRole('button',{name:'이 학교 함께 키우기'}).click();await expect(p.getByRole('heading',{name:'Google로 로그인'})).toBeVisible();await expect(p.getByLabel('선택한 학교')).toContainText(school.school_name)
  expect(count(calls,'/api/account/memberships')).toBe(0);expect(count(calls,'/api/growth/referral')).toBe(0)
  // Same-tab full-document return; OAuth itself is not executed or simulated as proven.
  await p.goto(base+'/account?mode=setup');await p.getByRole('button',{name:'이 학교를 등록 폼에 선택'}).click();await expect(p.locator('#school-query')).toHaveValue(new RegExp(school.school_name));await expect(p.getByLabel('졸업연도',{exact:true})).toHaveValue('');await p.getByLabel('졸업연도',{exact:true}).fill('2018');await p.getByRole('button',{name:'학교 이력 추가'}).click();await expect(p.getByRole('heading',{name:'내 학교',exact:true})).toBeVisible();expect(count(calls,'/api/account/memberships')).toBe(1)
  expect(await p.evaluate(()=>sessionStorage.getItem('sl_school_candidate_v1'))).toBeNull();await p.getByRole('button',{name:'친구 불러서 학교 키우기'}).click();await expect(p.getByRole('dialog')).toBeVisible();expect(count(calls,'/api/growth/referral')).toBe(0);await p.screenshot({path:'.local/growth-ux/journey-share.png',fullPage:false})
 })
 await test('candidate: blocked storage offers manual selection, no write',async(p,{calls})=>{await p.addInitScript(()=>Object.defineProperty(window,'sessionStorage',{get(){throw Error('blocked')}}));await p.goto(base+'/school/example-school');await p.getByRole('button',{name:'이 학교 함께 키우기'}).click();await expect(p.getByText(/이 탭에 학교 선택을 보관할 수 없어요/)).toBeVisible();expect(calls.some(c=>c.method==='POST')).toBe(false)})
 await test('candidate: existing school, explicit cancel, no duplicate save',async(p,{calls})=>{await intent(p);await p.goto(base+'/account?mode=member');await expect(p.getByText('이미 등록한 내 학교')).toBeVisible();await p.getByRole('button',{name:'학교 후보 지우기'}).click();expect(await p.evaluate(()=>sessionStorage.getItem('sl_school_candidate_v1'))).toBeNull();expect(count(calls,'/api/account/memberships')).toBe(0)})
 await test('candidate: missing lookup safe fallback',async(p)=>{await intent(p,'missing-school');await p.goto(base+'/account?mode=setup');await expect(p.getByText(/선택한 학교를 확인하지 못했어요/)).toBeVisible();await expect(p.locator('#school-query')).toHaveValue('')})
 await test('candidate: expired hint never pre-fills',async(p,{calls})=>{await intent(p,school.slug,Date.now()-100);await p.goto(base+'/account?mode=setup');await expect(p.locator('#school-query')).toHaveValue('');expect(count(calls,'/api/schools/selection','GET')).toBe(0)})
 await test('candidate: never overwrite ongoing inputs',async(p)=>{await intent(p);await p.route('**/api/schools/selection?*',async r=>{await new Promise(resolve=>setTimeout(resolve,700));await r.fulfill({json:{school}})});await p.goto(base+'/account?mode=setup');await p.locator('#school-query').fill('다른학교');await p.getByLabel('졸업연도',{exact:true}).fill('2001');await expect(p.getByRole('button',{name:'이 학교를 등록 폼에 선택'})).toBeDisabled();await expect(p.locator('#school-query')).toHaveValue('다른학교');await expect(p.getByLabel('졸업연도',{exact:true})).toHaveValue('2001')})
 await test('candidate: incomplete onboarding cannot save or auto-consent',async(p,{calls})=>{await intent(p);await p.goto(base+'/account?mode=new');await expect(p.getByRole('button',{name:'이 학교를 등록 폼에 선택'})).toBeDisabled();await expect(p.getByRole('button',{name:'학교 이력 추가'})).toBeDisabled();for(const checkbox of await p.getByRole('checkbox').all())await expect(checkbox).not.toBeChecked();expect(calls.some(c=>c.method==='POST')).toBe(false)})
 await test('share: opening/cancel 0 issuance, explicit prepare dedup, cancel no clipboard, reuse',async(p,{calls})=>{
  await p.addInitScript(()=>{window.__copied=[];Object.defineProperty(navigator,'share',{value:async()=>{throw new DOMException('cancel','AbortError')}});Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>window.__copied.push(t)}})})
  await sharePage(p);expect(count(calls,'/api/growth/referral')).toBe(0);await p.keyboard.press('Escape');await expect(p.getByRole('dialog')).not.toBeVisible();await expect(p.getByRole('button',{name:'친구 불러서 학교 키우기'})).toBeFocused();await p.getByRole('button',{name:'친구 불러서 학교 키우기'}).click();await p.getByRole('button',{name:'친구 링크 준비',exact:true}).dblclick();await p.getByRole('button',{name:'공유 앱 선택'}).click();await expect(p.getByText(/共有/)).toHaveCount(0);await expect(p.getByText('공유를 취소했어요. 자동 복사는 하지 않았어요.')).toBeVisible();expect(await p.evaluate(()=>window.__copied.length)).toBe(0);await p.getByRole('button',{name:'초대 문구와 링크 복사'}).click();const copied=await p.evaluate(()=>window.__copied[0]);expect(copied).toContain(school.school_name);expect(copied).toContain('스쿨러브아이');expect(copied).not.toContain('로컬 예시 사용자');expect(copied).not.toContain('2018');expect(count(calls,'/api/growth/referral')).toBe(1)
 })
 await test('share: permission-denied clipboard supplies selectable text, no native API fallback',async(p,{calls})=>{await p.addInitScript(()=>{Object.defineProperty(navigator,'share',{value:undefined});Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('denied')}}})});await sharePage(p);await p.getByRole('button',{name:'친구 링크 준비',exact:true}).click();await p.getByRole('button',{name:'초대 문구와 링크 복사'}).click();await expect(p.getByLabel('직접 복사할 문구')).toBeVisible();await p.getByRole('button',{name:'문구 전체 선택'}).click();expect(await p.getByLabel('직접 복사할 문구').evaluate(e=>e.selectionEnd-e.selectionStart)).toBeGreaterThan(20);expect(count(calls,'/api/growth/referral')).toBe(1)})
 await test('share: server error does not auto retry; general link has no referral',async(p,{calls})=>{await p.addInitScript(()=>{window.__copied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>window.__copied.push(t)}})});await p.route('**/api/growth/referral',r=>r.fulfill({status:403,json:{error:'ACCESS_DENIED'}}));await sharePage(p);await p.getByRole('button',{name:'친구 링크 준비',exact:true}).click();await expect(p.getByText(/친구 링크를 준비하지 못했어요/)).toBeVisible();await p.getByRole('button',{name:'추천 없이 일반 학교 링크 복사'}).click();expect((await p.evaluate(()=>window.__copied[0]))).not.toContain('#grow');expect(count(calls,'/api/growth/referral')).toBe(0) /* intercepted by explicit failure mock */})
 await test('share: expired in-memory link cleared without automatic issuance',async(p,{calls})=>{await p.route('**/api/growth/referral',r=>r.fulfill({json:{token:'a'.repeat(64),expiresIn:1}}));await sharePage(p);await p.getByRole('button',{name:'친구 링크 준비',exact:true}).click();await expect(p.getByRole('button',{name:'초대 문구와 링크 복사'})).toBeVisible();await expect(p.getByText(/링크가 만료됐어요/)).toBeVisible();await expect(p.getByRole('button',{name:'친구 링크 준비',exact:true})).toBeVisible();expect(count(calls,'/api/growth/referral')).toBe(0)})
 await test('connection labels localized, mutation controls not used',async(p,{calls})=>{await p.goto(base+'/connections');await expect(p.getByText('수락 대기',{exact:true})).toBeVisible();await expect(p.getByText(/같은 반/)).toBeVisible();expect(calls.every(c=>c.method==='GET')).toBe(true)})
 await test('share: native success and link-only copy reuse one prepared link',async(p,{calls})=>{await p.addInitScript(()=>{window.__shared=0;window.__copied=[];Object.defineProperty(navigator,'share',{value:async()=>{window.__shared++}});Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>window.__copied.push(t)}})});await sharePage(p);await p.getByRole('button',{name:'친구 링크 준비',exact:true}).click();await p.getByRole('button',{name:'공유 앱 선택'}).click();await expect(p.getByText('공유 창을 마쳤어요.')).toBeVisible();await p.getByRole('button',{name:'링크만 복사',exact:true}).click();expect(await p.evaluate(()=>window.__shared)).toBe(1);expect(await p.evaluate(()=>window.__copied[0].startsWith(location.origin+'/school/'))).toBe(true);expect(count(calls,'/api/growth/referral')).toBe(1)})
}finally{await mkdir('.local/growth-ux',{recursive:true});await writeFile('.local/growth-ux/functional.json',JSON.stringify(results,null,2));await browser.close()}
console.log(JSON.stringify(results,null,2));if(results.some(r=>r.result!=='PASS'))process.exitCode=1
