import {useState} from 'react'
const base='/.local/growth-ux/fantasy-applied'
const screens=[['home','홈','/?mode=guest'],['search','학교 찾기','/search'],['login','로그인','/login'],['onboarding','가입 단계','/onboarding'],['account','내 학교 · 계정','/account?mode=member'],['connections','내 연결','/connections'],['detail','연결 상세','/connections/fixture'],['share','친구에게 공유','/school/example-school?mode=member'],['guide-1','환영 안내','/account?mode=new'],['guide-2','가입 안내','/account?mode=new'],['guide-3','학교 상태 안내','/account?mode=new'],['guide-4','내 연결 안내','/account?mode=new'],...[1,2,4,7,10].map(l=>['school-'+l,'학교 Lv.'+l,'/school/example-school?level='+l])]
export default function VisualGallery(){const [mobile,setMobile]=useState(false);return <main style={{maxWidth:1440,margin:'auto',padding:'40px 24px',fontFamily:'sans-serif',color:'#24203d'}}>
 <p style={{color:'#936391',fontSize:13,letterSpacing:3}}>SCHOOLLOVE · FANTASY V3</p><h1 style={{fontSize:36,fontWeight:800,margin:'12px 0'}}>V3를 적용한 실제 화면 구성</h1><p style={{color:'#6e6680',lineHeight:1.8}}>모든 화면의 새 이미지와 영상을 한곳에 모았어요. 아래 화면은 실제 화면 구성에 예시 데이터를 넣은 로컬 미리보기입니다.</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:24,margin:'32px 0'}}>
  <section style={{padding:20,background:'#f4eaf4',borderRadius:24}}><h2 style={{fontSize:23,fontWeight:700,marginBottom:16}}>홈 · 판타지 학교</h2><img alt="V3 판타지 학교" src="/images/fantasy-v3/hero.webp" style={{width:'100%',aspectRatio:'4/3',objectFit:'cover',borderRadius:18}}/><p style={{marginTop:12}}>전체 배경 이미지 · 실제 홈에서는 별빛 효과를 켜고 끌 수 있어요.</p></section>
  <section style={{padding:20,background:'#25273c',color:'white',borderRadius:24}}><h2 style={{fontSize:23,fontWeight:700,marginBottom:16}}>학교 순위 · 공성전</h2><div style={{display:'flex',gap:16,alignItems:'center'}}><video controls playsInline muted loop poster="/images/scenes/siege-poster-v1.jpg" src="/videos/scenes/siege-loop-v1.mp4" style={{width:'45%',maxHeight:390,borderRadius:18}}/><div><p>자막·로고 없는 7.5초 배너 영상</p><p style={{marginTop:20}}><a href="/.local/growth-ux/scene-work/siege-clean-full.mp4" target="_blank" rel="noreferrer" style={{textDecoration:'underline'}}>27초 전체 편집본 보기 ↗</a></p></div></div></section>
 </div>
 <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,margin:'32px 0 20px'}}><h2 style={{fontSize:26,fontWeight:800}}>화면 전체 보기</h2><button onClick={()=>setMobile(!mobile)} style={{padding:'12px 20px',borderRadius:24,background:'#e9ddf5',fontWeight:700}}>{mobile?'PC 화면으로':'모바일 화면으로'}</button></div>
 <div style={{display:'grid',gridTemplateColumns:mobile?'repeat(auto-fit,minmax(230px,1fr))':'repeat(auto-fit,minmax(min(100%,450px),1fr))',gap:24}}>{screens.map(([id,title,url])=><article key={id} style={{minWidth:0,border:'1px solid #e7dfef',borderRadius:22,overflow:'hidden',background:'white'}}><div style={{padding:'16px 20px',display:'flex',justifyContent:'space-between'}}><h3 style={{fontWeight:700}}>{title}</h3><a href={url} target="_blank" rel="noreferrer" style={{fontSize:12,color:'#744893'}}>실제 화면 ↗</a></div><a href={`${base}/${id}-${mobile?390:1280}.png`} target="_blank" rel="noreferrer"><img src={`${base}/${id}-${mobile?390:1280}.png`} alt={`${title} ${mobile?'모바일':'PC'} 미리보기`} loading="lazy" style={{width:'100%',height:mobile?500:420,objectFit:'cover',objectPosition:'top',background:'#f6f0fb'}}/></a></article>)}</div>
 <p style={{marginTop:30,color:'#81748c'}}>이미지를 누르면 화면 전체를 크게 볼 수 있어요. 이 페이지의 학교와 연결 정보는 화면 확인을 위한 예시입니다.</p>
 </main>}
