import { fork } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const required = ['PGHOST', 'PGPORT', 'PGDATABASE', 'PGUSER', 'PGPASSWORD']
const env = { ...process.env }
if (required.some(key => !env[key])) throw new Error('PHASE10P_RESUME_DIRECT_TCP_CONFIG_MISSING')
const workerPath = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'phase10o-o', 'pg-worker.mjs')
function worker() { const child=fork(workerPath,[],{env,silent:true}); const state={child,ready:null,result:null,error:null,exit:null}; child.on('message',m=>{if(m?.type==='READY')state.ready=m;else if(m?.type==='RESULT')state.result=m;else if(m?.type==='ERROR')state.error=m}); child.on('exit',c=>{state.exit=c}); return state }
async function waitFor(predicate,workers,label){const deadline=Date.now()+20_000;while(!predicate()){const failure=workers.find(x=>x.error||(x.exit!==null&&!x.result));if(failure||Date.now()>=deadline){workers.filter(x=>x.exit===null).forEach(x=>x.child.kill('SIGTERM'));throw new Error(`PHASE10P_RESUME_${label}_${failure?.error?.code??failure?.exit??'TIMEOUT'}`)}await new Promise(r=>setTimeout(r,10))}}
async function run(sql,label){const w=worker();await waitFor(()=>w.ready,[w],`${label}_READY`);w.child.send({type:'GO',sql});await waitFor(()=>w.result&&w.exit===0,[w],`${label}_RESULT`);return w.result}
async function race(){const left=worker(),right=worker(),ws=[left,right];await waitFor(()=>left.ready&&right.ready,ws,'RACE_READY');if(left.ready.workerPid===right.ready.workerPid||left.ready.backendPid===right.ready.backendPid)throw new Error('PHASE10P_RESUME_NOT_INDEPENDENT');const digest="decode(repeat('b1',32),'hex')";const subject="'slb:v1:k01:google:'||translate(rtrim(encode("+digest+",'base64'),'='),'+/','-_')";left.child.send({type:'GO',sql:`SELECT public.record_verified_social_identity_from_upstream_leg((SELECT id FROM private.oauth_login_attempts WHERE safe_attempt_id='att_10p_resume_race_001'),'72000000-0000-4000-8000-000000000002','google',${subject},${digest},1) AS outcome;`});right.child.send({type:'GO',sql:`SELECT public.record_verified_social_identity_from_upstream_leg((SELECT id FROM private.oauth_login_attempts WHERE safe_attempt_id='att_10p_resume_race_002'),'73000000-0000-4000-8000-000000000002','google',${subject},${digest},1) AS outcome;`});await waitFor(()=>left.result&&right.result&&left.exit===0&&right.exit===0,ws,'RACE_RESULT');return{left,right}}

const raced=await race();const outcomes=[raced.left.result.rows[0]?.outcome,raced.right.result.rows[0]?.outcome].sort();if(outcomes.join(',')!=='IDENTITY_DECISION_IN_PROGRESS,PROVISIONAL_RESUME_READY')throw new Error(`PHASE10P_RESUME_RACE_OUTCOME_${outcomes.join('_')}`)
const read=await run(`SELECT count(*) FILTER(WHERE a.state='account_decided' AND l.status='verified' AND t.status='upstream_bound')::text AS winners,count(*) FILTER(WHERE a.state='failed_safe' AND l.status='rejected' AND t.status='rejected')::text AS safe_losers,(SELECT count(*) FROM private.private_accounts)::text AS accounts,(SELECT count(*) FROM private.social_identity_registry)::text AS identities,(SELECT count(*) FROM private.broker_authorization_codes)::text AS codes FROM private.oauth_login_attempts a JOIN private.upstream_login_legs l ON l.login_attempt_id=a.id JOIN private.downstream_authorization_transactions t ON t.login_attempt_id=a.id WHERE a.safe_attempt_id IN ('att_10p_resume_race_001','att_10p_resume_race_002');`,'READBACK');const row=read.rows[0];if(row?.winners!=='1'||row?.safe_losers!=='1'||row?.accounts!=='1'||row?.identities!=='1'||row?.codes!=='1')throw new Error('PHASE10P_RESUME_RACE_READBACK')
const issued=await run(`SELECT outcome FROM public.issue_transaction_bound_broker_authorization_code((SELECT t.id FROM private.downstream_authorization_transactions t JOIN private.oauth_login_attempts a ON a.id=t.login_attempt_id WHERE a.safe_attempt_id IN ('att_10p_resume_race_001','att_10p_resume_race_002') AND a.state='account_decided'),'74000000-0000-4000-8000-000000000001',decode(repeat('c7',32),'hex'),floor(extract(epoch FROM clock_timestamp()))::bigint-1,NULL,NULL,NULL,NULL,NULL);`,'ISSUE');if(issued.rows[0]?.outcome!=='AUTHORIZATION_CODE_CREATED')throw new Error('PHASE10P_RESUME_WINNER_CODE')
const final=await run(`SELECT (SELECT count(*) FROM private.private_accounts)::text AS accounts,(SELECT count(*) FROM private.social_identity_registry)::text AS identities,(SELECT count(*) FROM private.broker_authorization_codes)::text AS codes,(SELECT count(*) FROM private.broker_authorization_codes GROUP BY authorization_transaction_id HAVING count(*)>1)::text AS duplicate_codes;`,'FINAL');if(final.rows[0]?.accounts!=='1'||final.rows[0]?.identities!=='1'||final.rows[0]?.codes!=='2'||final.rows[0]?.duplicate_codes!==null)throw new Error('PHASE10P_RESUME_DUPLICATION')
process.stdout.write('PHASE10P_PROVISIONAL_RESUME_CONCURRENCY_OK winners=1 safe_losers=1 accounts=1 identities=1 duplicate_codes=0 deadlocks=0 raw_unique_violations=0\n')
