import { describe,expect,it } from 'vitest'
import { assessBetaReadiness, BetaFeedbackSchema, BetaSetupSchema, feedbackTextIsSafe, isSyntheticModeAllowed, maskSmallAggregate } from './betaOperations'

describe('controlled beta operations policy',()=>{
  it('masks every segment below ten',()=>{expect(maskSmallAggregate(9)).toEqual({count:null,masked:true,label:'10명 미만'});expect(maskSmallAggregate(10)).toEqual({count:10,masked:false,label:'10'})})
  it('rejects identifiers and query-bearing paths in feedback',()=>{for(const value of ['name@example.com','@somebody','https://example.com','010-1234-5678'])expect(feedbackTextIsSafe(value)).toBe(false);expect(BetaFeedbackSchema.safeParse({programId:crypto.randomUUID(),kind:'error',description:'버튼을 누르면 화면이 멈춥니다',pagePath:'/account',coarseBrowser:'chrome',coarseDevice:'mobile'}).success).toBe(true);expect(BetaFeedbackSchema.safeParse({programId:crypto.randomUUID(),kind:'error',description:'오류입니다',pagePath:'/search?q=name'}).success).toBe(false)})
  it('requires feature dependency ordering',()=>{const base={draftKey:'beta_01',name:'Beta',startsAt:null,endsAt:null,maxUsers:20,targetScope:'adult graduates',invitePolicy:{maxUsesPerInvite:1,expiresInDays:7},approvalWaitlistEnabled:true,stopConditions:{RLS_FAILURE:true},operatorMemo:'',status:'validated' as const};expect(BetaSetupSchema.safeParse({...base,enabledFeatures:['messaging']}).success).toBe(false);expect(BetaSetupSchema.safeParse({...base,enabledFeatures:['people_search','connection_request','messaging']}).success).toBe(true)})
  it('allows synthetic data only behind an explicit non-production flag',()=>{expect(isSyntheticModeAllowed({CONTROLLED_BETA_SYNTHETIC_MODE:'enabled',VERCEL_ENV:'preview'})).toBe(true);expect(isSyntheticModeAllowed({CONTROLLED_BETA_SYNTHETIC_MODE:'enabled',VERCEL_ENV:'production'})).toBe(false);expect(isSyntheticModeAllowed({VERCEL_ENV:'preview'})).toBe(false)})
  it('fails readiness closed on privacy, health, RLS, urgent work or live payment',()=>{expect(assessBetaReadiness({healthOk:false,rlsOk:true,openUrgentTasks:0,privacyIncidents:0,paymentLive:false,lifecycleComplete:true})).toBe('blocked');expect(assessBetaReadiness({healthOk:true,rlsOk:true,openUrgentTasks:1,privacyIncidents:0,paymentLive:false,lifecycleComplete:true})).toBe('internal_only');expect(assessBetaReadiness({healthOk:true,rlsOk:true,openUrgentTasks:0,privacyIncidents:0,paymentLive:false,lifecycleComplete:true})).toBe('limited_beta')})
})
