import { fork } from 'node:child_process'
import { generateKeyPairSync, sign } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { DarkBrokerOrchestrator } from '../../lib/auth/social-broker/dark-orchestrator.ts'
import { createDurableProviderVerifier } from '../../lib/auth/social-broker/durable-provider-verifier.ts'
import { createSyntheticClient, DarkOidcHttpIssuer } from '../../lib/auth/social-broker/http.ts'
import { prepareTransactionBoundBrokerCode } from '../../lib/auth/social-broker/transaction-bound-code-issuance.ts'
import { GOOGLE_OIDC_METADATA, KAKAO_OIDC_METADATA } from '../../lib/auth/social-broker/upstream-adapters.ts'

const workerPath = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'phase10o-o', 'pg-worker.mjs')
const q = value => value === null ? 'NULL' : `'${String(value).replaceAll("'", "''")}'`
const hex = value => Buffer.from(value).toString('hex')
const bytes = value => value === null ? null : Buffer.from(String(value).replace(/^\\x/, ''), 'hex')
function durableContinuationRow(row) {
  return {
    outcome: row.outcome, transactionId: row.transaction_id, attemptId: row.attempt_id, provider: row.provider,
    clientId: row.client_id, redirectUri: row.redirect_uri, legId: row.leg_id,
    clientBindingDigest: bytes(row.client_binding_digest), stateDigest: bytes(row.state_digest), nonceDigest: bytes(row.nonce_digest),
    pkceS256Challenge: row.pkce_s256_challenge, pkceVerifierCiphertext: bytes(row.pkce_verifier_ciphertext), pkceVerifierIv: bytes(row.pkce_verifier_iv), pkceVerifierKeyVersion: row.pkce_verifier_key_version === null ? null : Number(row.pkce_verifier_key_version),
    continuationCiphertext: bytes(row.continuation_ciphertext), continuationIv: bytes(row.continuation_iv), continuationKeyVersion: row.continuation_key_version === null ? null : Number(row.continuation_key_version),
  }
}
function sql(name, statement) {
  return new Promise((resolve, reject) => {
    const child = fork(workerPath, [], { env: process.env, silent: true }); const timer = setTimeout(() => { child.kill(); reject(new Error(`${name}_TIMEOUT`)) }, 15_000)
    child.on('message', message => { if (message?.type === 'READY') child.send({ type: 'GO', sql: statement }); if (message?.type === 'RESULT') { clearTimeout(timer); resolve(message.rows) }; if (message?.type === 'ERROR') { clearTimeout(timer); reject(new Error(`${name}_${message.code}`)) } })
    child.on('error', reject)
  })
}
const config = provider => ({ clientId: `q-${provider}-upstream`, redirectUri: `https://broker.invalid/${provider}/callback` })
const clients = ['google', 'kakao', 'naver'].map(provider => createSyntheticClient(`slb-supabase-${provider}`, `q-${provider}-secret`, `https://consumer.invalid/${provider}/return`, provider))
function port() {
  let lastCallback = null; let lastContinuationOutcome = null
  return {
  createAttempt: async input => (await sql('CREATE_ATTEMPT', `SELECT public.create_social_login_attempt(${q(input.safeAttemptId)},${q(input.provider)},to_timestamp(${input.expiresAt})) AS id`))[0].id,
    createTransaction: async input => (await sql('CREATE_TX', `SELECT outcome FROM public.create_downstream_authorization_transaction(${q(input.transactionId)},${q(input.loginAttemptId)},decode(${q(hex(input.brokerHandleDigest))},'hex'),${q(input.clientId)},${q(input.redirectUri)},'code',${q(input.requestedScopes)},${q(input.pkceS256Challenge)},'S256',${q(input.downstreamNonce)},${q(input.downstreamState)},to_timestamp(${input.expiresAt}))`))[0].outcome,
    resolveDurableContinuation: async digest => { const result = durableContinuationRow((await sql('RESOLVE_CONTINUATION', `SELECT * FROM public.resolve_durable_continuation_by_digest(decode(${q(hex(digest))},'hex'))`))[0]); lastContinuationOutcome = result.outcome; return result },
    createOrResumeDurableContinuation: async input => { const result = durableContinuationRow((await sql('CREATE_OR_RESUME_CONTINUATION', `SELECT * FROM public.create_or_resume_durable_upstream_continuation(decode(${q(hex(input.continuationDigest))},'hex'),${q(input.leg.legId)},${q(input.leg.provider)},decode(${q(hex(input.leg.clientBindingDigest))},'hex'),decode(${q(hex(input.leg.stateDigest))},'hex'),${input.leg.nonceDigest ? `decode(${q(hex(input.leg.nonceDigest))},'hex')` : 'NULL'},${q(input.leg.pkce?.challenge ?? null)},${input.leg.pkce ? `decode(${q(hex(input.leg.pkce.ciphertext))},'hex')` : 'NULL'},${input.leg.pkce ? `decode(${q(hex(input.leg.pkce.iv))},'hex')` : 'NULL'},${input.leg.pkce?.keyVersion ?? 'NULL'},decode(${q(hex(input.continuation.ciphertext))},'hex'),decode(${q(hex(input.continuation.iv))},'hex'),${input.continuation.keyVersion})`))[0]); lastContinuationOutcome = result.outcome; return result },
    claimCallback: async input => { const row = (await sql('CLAIM_CALLBACK', `SELECT * FROM public.claim_upstream_login_callback_by_state(${q(input.provider)},decode(${q(hex(input.clientBindingDigest))},'hex'),decode(${q(hex(input.stateDigest))},'hex'))`))[0]; lastCallback = { attemptId: row.attempt_id, legId: row.leg_id }; return { outcome: row.outcome, attemptId: row.attempt_id, legId: row.leg_id, provider: row.provider, nonceDigest: bytes(row.nonce_digest), pkceS256Challenge: row.pkce_s256_challenge, pkceVerifierCiphertext: bytes(row.pkce_verifier_ciphertext), pkceVerifierIv: bytes(row.pkce_verifier_iv), pkceVerifierKeyVersion: row.pkce_verifier_key_version === null ? null : Number(row.pkce_verifier_key_version) } },
    failClaimedUpstreamLeg: async input => (await sql('FAIL_LEG', `SELECT public.fail_upstream_login_leg(${q(input.attemptId)},${q(input.legId)},${q(input.reason)}) AS outcome`))[0].outcome,
    recordVerifiedIdentity: async input => (await sql('RECORD_IDENTITY', `SELECT public.record_verified_social_identity_from_upstream_leg(${q(input.attemptId)},${q(input.legId)},${q(input.provider)},${q(input.brokerSubject)},decode(${q(hex(input.subjectDigest))},'hex'),${input.subjectKeyVersion}) AS outcome`))[0].outcome,
    lastCallback: () => lastCallback, lastContinuationOutcome: () => lastContinuationOutcome,
  }
}
function orchestrator(keys) { const persistence = port(); return { persistence, value: new DarkBrokerOrchestrator({ clients, persistence, upstream: { google: config('google'), kakao: config('kakao'), naver: config('naver') }, keys, now: () => Math.floor(Date.now() / 1000) }) } }
function runtimeVerifier(provider, rawNonce, authorizationCode, keys, failureClass, expectedAuthorizationCode = authorizationCode, upstreamSubject = `synthetic-${provider}-subject`) {
  let exchanges = 0; let jwks = 0
  if (provider === 'naver') return { verifier: createDurableProviderVerifier({ upstream: { google: config('google'), kakao: config('kakao'), naver: config('naver') }, pkceKey: keys.upstreamPkce, now: () => Math.floor(Date.now() / 1000), transport: { exchangeCode: async request => { exchanges += 1; if (request.provider !== 'naver' || request.authorizationCode !== expectedAuthorizationCode || request.clientId !== config('naver').clientId) throw new Error('SYNTHETIC_TRANSPORT_REJECTED'); if (failureClass === 'token_http') return { status: 500, contentType: 'application/json', body: '{}', url: request.tokenEndpoint }; if (failureClass === 'token_malformed') return { status: 200, contentType: 'application/json', body: '{', url: request.tokenEndpoint }; if (failureClass === 'token_missing_access') return { status: 200, contentType: 'application/json', body: '{}', url: request.tokenEndpoint }; return { status: 200, contentType: 'application/json', body: JSON.stringify({ access_token: 'synthetic-memory-only' }), url: failureClass === 'token_wrong_url' ? 'https://unexpected.invalid/' : request.tokenEndpoint } }, fetchJwks: async () => { throw new Error('unused') }, fetchNaverProfile: async request => { if (failureClass === 'profile_http') return { status: 500, contentType: 'application/json', body: '{}', url: request.profileEndpoint }; if (failureClass === 'profile_malformed') return { status: 200, contentType: 'application/json', body: '{', url: request.profileEndpoint }; if (failureClass === 'profile_wrong_url') return { status: 200, contentType: 'application/json', body: JSON.stringify({ resultcode: '00', response: { id: upstreamSubject } }), url: 'https://unexpected.invalid/' }; if (failureClass === 'profile_resultcode') return { status: 200, contentType: 'application/json', body: JSON.stringify({ resultcode: '01', response: { id: upstreamSubject } }), url: request.profileEndpoint }; if (failureClass === 'profile_missing_subject') return { status: 200, contentType: 'application/json', body: JSON.stringify({ resultcode: '00', response: {} }), url: request.profileEndpoint }; return { status: 200, contentType: 'application/json', body: JSON.stringify({ resultcode: '00', response: { id: upstreamSubject } }), url: request.profileEndpoint } } } }), counts: () => ({ exchanges, jwks }) }
  const pair = generateKeyPairSync('rsa', { modulusLength: 2048 }); const kid = 'q-runtime-kid'; const issuer = provider === 'google' ? GOOGLE_OIDC_METADATA.issuers[0] : KAKAO_OIDC_METADATA.issuer
  const now = Math.floor(Date.now() / 1000); const payload = { iss: failureClass === 'wrong_issuer' ? 'https://unexpected.invalid' : issuer, aud: failureClass === 'wrong_audience' ? 'unexpected-client' : config(provider).clientId, sub: upstreamSubject, iat: failureClass === 'future_iat' ? now + 61 : now - 1, exp: failureClass === 'expired_token' ? now - 1 : now + 60, auth_time: now - 2, nonce: failureClass === 'wrong_nonce' ? 'unexpected-nonce' : rawNonce }; const tokenKid = failureClass === 'unknown_kid' ? 'unknown-kid' : kid; const head = Buffer.from(JSON.stringify({ alg: 'RS256', kid: tokenKid }), 'utf8').toString('base64url'); const body = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64url'); const signingKey = failureClass === 'bad_signature' ? generateKeyPairSync('rsa', { modulusLength: 2048 }).privateKey : pair.privateKey; const token = `${head}.${body}.${sign('RSA-SHA256', Buffer.from(`${head}.${body}`, 'ascii'), signingKey).toString('base64url')}`; const jwk = { ...(pair.publicKey.export({ format: 'jwk' })), kid, use: 'sig', alg: 'RS256' }
  return { verifier: createDurableProviderVerifier({ upstream: { google: config('google'), kakao: config('kakao'), naver: config('naver') }, pkceKey: keys.upstreamPkce, now: () => now, transport: { exchangeCode: async request => { exchanges += 1; if (request.provider !== provider || request.authorizationCode !== expectedAuthorizationCode || !request.codeVerifier) throw new Error('SYNTHETIC_TRANSPORT_REJECTED'); if (failureClass === 'token_malformed') return { status: 200, contentType: 'application/json', body: '{', url: request.tokenEndpoint }; return { status: 200, contentType: 'application/json', body: JSON.stringify({ id_token: token }), url: failureClass === 'token_wrong_url' ? 'https://unexpected.invalid/' : request.tokenEndpoint } }, fetchJwks: async request => { jwks += 1; return { status: 200, contentType: 'application/json', body: failureClass === 'jwks_malformed' ? '{' : JSON.stringify({ keys: [jwk] }), url: request.jwksUri } }, fetchNaverProfile: async () => { throw new Error('unused') } } }), counts: () => ({ exchanges, jwks }) }
}
async function finalize(input, keys) {
  const row = (await sql('ISSUANCE_CONTEXT', `SELECT authorization_transaction_id::text,login_attempt_id::text,client_id,redirect_uri,pkce_s256_challenge,downstream_nonce,downstream_state FROM public.get_transaction_bound_broker_code_issuance_context(${q(input.trustedAttemptId)})`))[0]
  if (!row) throw new Error('Q_FINALIZATION_CONTEXT_REJECTED')
  const prepared = prepareTransactionBoundBrokerCode({ context: { authorizationTransactionId: row.authorization_transaction_id, loginAttemptId: row.login_attempt_id, clientId: row.client_id, redirectUri: row.redirect_uri, pkceS256Challenge: row.pkce_s256_challenge, downstreamNonce: row.downstream_nonce, downstreamState: row.downstream_state }, authenticationTime: input.authenticationTime, ...(row.downstream_nonce === null ? {} : { downstreamNonceKey: keys.downstreamNonce }) })
  const nonce = prepared.database.code.downstreamNonce
  const issued = (await sql('ISSUE_CODE', `SELECT outcome,downstream_state FROM public.issue_transaction_bound_broker_authorization_code(${q(prepared.database.authorizationTransactionId)},${q(prepared.database.code.codeId)},decode(${q(hex(prepared.database.code.codeDigest))},'hex'),${prepared.database.code.authenticationTime},${q(prepared.database.downstreamNonceProof)},${nonce ? `decode(${q(hex(nonce.digest))},'hex')` : 'NULL'},${nonce ? `decode(${q(hex(nonce.ciphertext))},'hex')` : 'NULL'},${nonce ? `decode(${q(hex(nonce.iv))},'hex')` : 'NULL'},${nonce?.keyVersion ?? 'NULL'})`))[0]
  if (issued?.outcome !== 'AUTHORIZATION_CODE_CREATED' || issued.downstream_state !== row.downstream_state) throw new Error('Q_FINALIZATION_ISSUE_REJECTED')
  return { authorizationCode: prepared.response.authorizationCode, redirectUri: row.redirect_uri, downstreamState: prepared.response.downstreamState }
}
async function token(input, keys) {
  const client = clients.find(value => value.clientId === input.clientId) ?? (input.tokenOptions?.allowUnknownClient ? clients[0] : undefined); if (!client) throw new Error('Q_TOKEN_CLIENT_REJECTED')
  let consumeCalls = 0
  const issuer = new DarkOidcHttpIssuer({ issuer: 'https://dark-broker.invalid', registry: { clients: [client], nonceKey: keys.downstreamNonce, authorize: async () => { throw new Error('unused') }, consumeCode: async request => { consumeCalls += 1; const row = (await sql('CONSUME_CODE', `SELECT outcome,broker_subject,authentication_time,encode(downstream_nonce_digest,'hex') AS nonce_digest,encode(downstream_nonce_ciphertext,'hex') AS nonce_ciphertext,encode(downstream_nonce_iv,'hex') AS nonce_iv,downstream_nonce_key_version,code_id::text FROM public.consume_broker_authorization_code(decode(${q(hex(request.codeDigest))},'hex'),${q(request.clientId)},${q(request.redirectUri)},${q(request.pkceS256Challenge)})`))[0]; if (row?.outcome !== 'AUTHORIZATION_CODE_CONSUMED') return null; return { outcome: 'AUTHORIZATION_CODE_CONSUMED', subject: row.broker_subject, authenticationTime: Number(row.authentication_time), codeId: row.code_id, downstreamNonce: row.nonce_digest === null ? null : { digest: bytes(row.nonce_digest), ciphertext: bytes(row.nonce_ciphertext), iv: bytes(row.nonce_iv), keyVersion: Number(row.downstream_nonce_key_version) } } } } })
  const options = input.tokenOptions ?? {}
  const body = new URLSearchParams({ grant_type: 'authorization_code', client_id: options.clientId ?? client.clientId, client_secret: options.clientSecret ?? `q-${input.provider}-secret`, code: options.authorizationCode ?? input.authorizationCode, redirect_uri: options.redirectUri ?? input.redirectUri, code_verifier: options.downstreamVerifier ?? input.downstreamVerifier })
  if (options.basicClientId !== undefined || options.basicSecret !== undefined) body.delete('client_id'), body.delete('client_secret')
  if (options.postCredentialsWithBasic) body.set('client_id', options.clientId ?? client.clientId), body.set('client_secret', options.clientSecret ?? `q-${input.provider}-secret`)
  const headers = { 'content-type': options.contentType ?? 'application/x-www-form-urlencoded; charset=UTF-8' }
  if (options.basicClientId !== undefined || options.basicSecret !== undefined) headers.authorization = `Basic ${Buffer.from(`${options.basicClientId ?? client.clientId}:${options.basicSecret ?? `q-${input.provider}-secret`}`, 'utf8').toString('base64')}`
  const response = await issuer.tokenRequest(new Request('https://dark-broker.invalid/oauth/token', { method: 'POST', headers, body }))
  const responseBody = await response.text(); const protocol = responseBody ? JSON.parse(responseBody) : null
  if (options.expectNegative) return { status: response.status, error: protocol?.error ?? null, consumeCalls }
  if (response.status !== 200) throw new Error('Q_TOKEN_EXCHANGE_REJECTED')
  const payload = protocol; const tokenPayload = JSON.parse(Buffer.from(payload.id_token.split('.')[1], 'base64url').toString('utf8'))
  const replay = await issuer.tokenRequest(new Request('https://dark-broker.invalid/oauth/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body }))
  if (replay.status !== 400 || consumeCalls !== 2) throw new Error('Q_TOKEN_REPLAY_REJECTED')
  return { claims: tokenPayload, consumeCalls }
}
process.once('message', async input => { try { const keys = { upstreamPkce: { version: 1, material: Buffer.from(input.keys.upstreamPkce, 'base64') }, upstreamContinuation: { version: 1, material: Buffer.from(input.keys.upstreamContinuation, 'base64') }, downstreamNonce: { version: 1, material: Buffer.from(input.keys.downstreamNonce, 'base64') }, brokerSubject: Buffer.from(input.keys.brokerSubject, 'base64'), brokerSubjectKeyVersion: 1 }; const current = orchestrator(keys); if (input.stage === 'A') { const out = await current.value.begin(new URL(input.url)); process.send({ ok: true, value: out }) } else if (input.stage === 'B_RESOLVE_ONLY') { const digest = (await import('../../lib/auth/social-broker/authorization-transaction.ts')).downstreamAuthorizationBoundHandleDigest(input.brokerHandle, input.browserBindingSecret); const out = await current.persistence.resolveDurableContinuation(digest); process.send({ ok: true, value: { outcome: out.outcome } }) } else if (input.stage === 'B') { const out = await current.value.continueFromHandle({ brokerHandle: input.brokerHandle, browserBindingSecret: input.browserBindingSecret }); process.send({ ok: true, value: { ...out, durableOutcome: current.persistence.lastContinuationOutcome() } }) } else if (input.stage === 'C') { const verifierKeys = input.failureClass === 'wrong_durable_pkce_key' ? { ...keys, upstreamPkce: { ...keys.upstreamPkce, material: Buffer.alloc(32, 0) } } : keys; const transport = runtimeVerifier(input.provider, input.rawNonce, input.authorizationCode, verifierKeys, input.failureClass, input.expectedAuthorizationCode, input.upstreamSubject); const verifier = input.failureClass === 'tampered_pkce_ciphertext' ? { verify: context => transport.verifier.verify({ ...context, pkce: context.pkce && { ...context.pkce, ciphertext: Buffer.concat([context.pkce.ciphertext, Buffer.from([0])]) } }) } : transport.verifier; const outcome = await current.value.callback({ provider: input.provider, callbackUrl: input.callbackUrl, verifier }); process.send({ ok: true, value: { outcome, counts: transport.counts(), trustedAttemptId: current.persistence.lastCallback()?.attemptId ?? null } }) } else if (input.stage === 'D') process.send({ ok: true, value: await finalize(input, keys) }); else if (input.stage === 'E') process.send({ ok: true, value: await token(input, keys) }); else throw new Error('Q_STAGE_INVALID') } catch (error) { process.send({ ok: false, error: error instanceof Error ? error.message : 'Q_STAGE_FAILURE' }) } finally { process.disconnect(); process.exit() } })
