import { readFileSync } from 'node:fs';import { join } from 'node:path';import { describe,expect,it } from 'vitest'
const source=(path:string)=>readFileSync(join(process.cwd(),path),'utf8')

describe('PHASE 10I route and privacy boundaries',()=>{
  it('protects every admin API internally and disables caching',()=>{for(const path of ['app/api/admin/beta/route.ts','app/api/admin/beta/report/route.ts','app/api/admin/beta/synthetic/route.ts']){const value=source(path);expect(value).toContain('requireAdminSession');expect(value).toContain('no-store')}})
  it('returns 404 before auth when synthetic mode is not explicitly allowed',()=>{const route=source('app/api/admin/beta/synthetic/route.ts');expect(route.indexOf('if(!isSyntheticModeAllowed())')).toBeLessThan(route.indexOf("if(!(await requireAdminSession(request)))"));expect(route).toContain("status:404")})
  it('keeps feedback owner-scoped and identifier filtered',()=>{const route=source('app/api/beta/feedback/route.ts');expect(route).toContain(".eq('owner_user_id',auth.user.id)");expect(route).toContain('BetaFeedbackSchema');expect(source('lib/policy/betaOperations.ts')).toContain('PERSONAL_OR_EXTERNAL_IDENTIFIER_NOT_ALLOWED')})
  it('keeps all operator pages private',()=>{for(const page of ['setup','users','schools','advertisers','tasks','readiness','report'])expect(source(`app/admin/beta/${page}/page.tsx`)).toContain('privateAdminMetadata')})
  it('never exposes raw identity fields from the admin aggregation layer',()=>{const helper=source('lib/betaOperations.ts');expect(helper).not.toMatch(/\.select\([^)]*(email|instagram|display_name|search_query|message|ip_address)/i);expect(helper).toContain('safeRef')})
  it('neutralizes CSV formulas through the established csvSafe helper',()=>{const helper=source('lib/betaOperations.ts');expect(helper).toContain("import { csvSafe }");expect(helper).toContain('row.map(csvSafe)')})
  it('supports only selected-school setup and safe controlled-beta actions',()=>{const route=source('app/api/admin/beta/route.ts');const policy=source('lib/policy/betaOperations.ts');const helper=source('lib/betaOperations.ts');expect(route).toContain('schoolQuery');expect(policy).toContain('targetSchoolId');expect(policy).toContain("action:z.literal('start_program')");expect(policy).toContain("action:z.literal('reactivate_program')");expect(helper).toContain('safeDbError');expect(helper).not.toContain('throw new Error(error.message)')})
  it('returns only allowlisted membership boundary codes',()=>{const route=source('app/api/account/memberships/route.ts');const launch=source('lib/publicAccountLaunch.ts');expect(route).toContain('getSafeMembershipError');expect(launch).toContain('SCHOOL_OUTSIDE_BETA_SCOPE');expect(launch).toContain('SECOND_SCHOOL_NOT_ALLOWED');expect(route).not.toContain('error.message }, { status: 500')})
  it('keeps legacy programs out of controlled program selection and raw identities out of school state',()=>{const ui=source('app/admin/beta/_components/ControlledBetaConsole.tsx');expect(ui).toContain('item.snapshot_backed');expect(ui).toContain('program.selected_school?.school_name');expect(ui).not.toMatch(/selected_school.*email|selected_school.*instagram/i)})
})
