'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'

type View='setup'|'users'|'schools'|'advertisers'|'tasks'|'readiness'|'report'
type State={programs:any[];drafts:any[];members:any[];memberSummary:Record<string,{count:number|null;masked:boolean;label:string}>;feedback:any[];tasks:any[];campaigns:any[];aggregates:any[];readiness:any[];advertisers:{requests:any[];orders:any[]};incidents:any[];privacy:Record<string,unknown>}
type Synthetic={mode:string;users:Array<{ref:string;status:string;stage:string}>;lifecycle:string[];counts:{profiles:number;payments:number;publicLaunches:number}}
const emptyState:State={programs:[],drafts:[],members:[],memberSummary:{},feedback:[],tasks:[],campaigns:[],aggregates:[],readiness:[],advertisers:{requests:[],orders:[]},incidents:[],privacy:{minimumAggregate:10}}
const nav:[View,string][]=[['setup','시작 마법사'],['users','베타 사용자'],['schools','첫 학교'],['advertisers','첫 광고주'],['tasks','피드백·작업 큐'],['readiness','중단·준비도'],['report','일일 보고']]
const input='w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm'
const card='rounded-2xl border border-gray-200 bg-white p-5 shadow-sm'

export default function ControlledBetaConsole({view}:{view:View}) {
  const [state,setState]=useState<State|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('')
  const [synthetic,setSynthetic]=useState<Synthetic|null>(null)
  const load=useCallback(async()=>{if(new URLSearchParams(window.location.search).get('synthetic')==='1'){const response=await fetch('/api/admin/beta/synthetic',{cache:'no-store'});if(!response.ok)throw new Error('합성 운영 모드는 이 환경에서 사용할 수 없습니다.');setSynthetic(await response.json());setState(emptyState);return}const response=await fetch('/api/admin/beta',{cache:'no-store'});if(!response.ok)throw new Error('운영 데이터를 불러오지 못했습니다.');setState(await response.json())},[])
  useEffect(()=>{load().catch(reason=>setError(String(reason)))},[load])
  async function mutate(payload:Record<string,unknown>){setError('');setNotice('');try{const response=await fetch('/api/admin/beta',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==='string'?body.error:'작업이 거부되었습니다.');setNotice('변경을 감사 로그와 함께 반영했습니다.');await load();return body}catch(reason){setError(reason instanceof Error?reason.message:'작업이 거부되었습니다.');return null}}
  if(!state)return <p role="status">{error||'제한 베타 운영 상태를 확인하고 있습니다.'}</p>
  if(synthetic)return <div className="space-y-6">
    <a className="inline-block rounded-full border bg-white px-4 py-2 text-sm" href="/admin/beta/setup">실제 운영 화면으로 돌아가기</a>
    <section className="rounded-2xl border-2 border-dashed border-blue-300 bg-blue-50 p-5" data-testid="synthetic-preview"><h2 className="text-xl font-black">TEST 합성 운영 미리보기</h2><p className="mt-2 text-sm">실제 이메일·Instagram·결제·Production row 없이 lifecycle을 확인합니다.</p><p className="mt-2 rounded-lg bg-white p-3 text-sm font-bold">읽기 전용 미리보기입니다. 실제 조회·저장·승인·중단 작업은 이 화면에서 실행할 수 없습니다.</p><div className="mt-4 flex flex-wrap gap-2">{synthetic.lifecycle.map((item,index)=><span key={item} className="rounded-full bg-white px-3 py-2 text-sm">{index+1}. {item}</span>)}</div><p className="mt-4 text-sm">생성된 실제 profile {synthetic.counts.profiles} · payment {synthetic.counts.payments} · public launch {synthetic.counts.publicLaunches}</p></section>
  </div>
  const program=state.programs.find(item=>item.status==='active')??state.programs[0]
  return <div className="space-y-6">
    <nav aria-label="제한 베타 운영" className="flex gap-2 overflow-x-auto pb-2">{nav.map(([key,label])=><a key={key} href={`/admin/beta/${key}`} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm ${view===key?'bg-gray-950 text-white':'bg-white'}`}>{label}</a>)}</nav>
    <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><strong>통제 상태:</strong> 일반 공개·자동 초대·실결제는 꺼져 있습니다. 운영 조치는 승인된 성인 beta member에게만 적용됩니다.</div>
    {notice?<p role="status" className="rounded-xl border border-green-200 bg-green-50 p-3 text-sm">{notice}</p>:null}{error?<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm">{error}</p>:null}
    {view==='setup'?<SetupView state={state} mutate={mutate}/>:null}
    {view==='users'?<UsersView state={state} mutate={mutate}/>:null}
    {view==='schools'?<SchoolsView state={state} programId={program?.id} mutate={mutate}/>:null}
    {view==='advertisers'?<AdvertisersView state={state}/>:null}
    {view==='tasks'?<TasksView state={state} programId={program?.id} mutate={mutate}/>:null}
    {view==='readiness'?<ReadinessView state={state} programId={program?.id} mutate={mutate}/>:null}
    {view==='report'?<ReportView state={state}/>:null}
  </div>
}

function SetupView({state,mutate}:{state:State;mutate:(payload:Record<string,unknown>)=>Promise<any>}){
  const draft=state.drafts[0]
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const features=form.getAll('features').map(String);await mutate({action:'save_setup',setup:{id:draft?.id??null,draftKey:String(form.get('draftKey')),name:String(form.get('name')),startsAt:form.get('startsAt')?new Date(String(form.get('startsAt'))).toISOString():null,endsAt:form.get('endsAt')?new Date(String(form.get('endsAt'))).toISOString():null,maxUsers:Number(form.get('maxUsers')),targetScope:String(form.get('targetScope')),enabledFeatures:features,invitePolicy:{maxUsesPerInvite:Number(form.get('maxUsesPerInvite')),expiresInDays:Number(form.get('expiresInDays'))},approvalWaitlistEnabled:true,stopConditions:{PRIVACY_EXPOSURE:true,RLS_FAILURE:true,HEALTH_FAILURE:true},operatorMemo:String(form.get('memo')??''),status:String(form.get('status'))}})}
  return <section className={card}><h2 className="text-xl font-black">제한 베타 시작 마법사</h2><p className="mt-2 text-sm text-gray-600">미리보기와 위험 경고를 확인한 뒤 검증합니다. 활성화해도 프로그램은 paused로 생성되며 초대나 공개 기능은 켜지지 않습니다.</p><a className="mt-3 inline-block rounded-lg border border-blue-300 px-3 py-2 text-sm text-blue-800" href="/admin/beta/setup?synthetic=1">TEST 합성 lifecycle 미리보기</a>
    <form onSubmit={event=>void submit(event)} className="mt-5 grid gap-4 md:grid-cols-2">
      <label>프로그램 키<input className={input} name="draftKey" defaultValue={draft?.draft_key??'controlled_beta_01'} required pattern="[a-z0-9][a-z0-9_-]{2,39}"/></label>
      <label>프로그램 이름<input className={input} name="name" defaultValue={draft?.name??'성인 제한 베타'} required/></label>
      <label>시작 시각<input className={input} name="startsAt" type="datetime-local"/></label><label>종료 시각<input className={input} name="endsAt" type="datetime-local"/></label>
      <label>최대 사용자 수<input className={input} name="maxUsers" type="number" min="1" max="1000" defaultValue={draft?.max_users??20}/></label><label>대상 범위<input className={input} name="targetScope" defaultValue={draft?.target_scope??'운영자가 확인한 성인 졸업생'} required/></label>
      <label>초대당 사용 수<input className={input} name="maxUsesPerInvite" type="number" min="1" max="100" defaultValue="1"/></label><label>초대 만료 일수<input className={input} name="expiresInDays" type="number" min="1" max="30" defaultValue="7"/></label>
      <fieldset className="md:col-span-2"><legend className="font-semibold">최소 허용 기능</legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{['account_registration','private_profile','people_search','connection_request','messaging','instagram_permission','promotion_application','promotion_operations'].map(feature=><label key={feature} className="rounded-lg border p-3 text-sm"><input type="checkbox" name="features" value={feature} defaultChecked={['account_registration','private_profile'].includes(feature)}/> {feature}</label>)}</div></fieldset>
      <label className="md:col-span-2">운영 메모<textarea className={input} name="memo" rows={4} defaultValue={draft?.operator_memo??''}/></label>
      <label>저장 상태<select className={input} name="status" defaultValue={draft?.status==='validated'?'validated':'draft'}><option value="draft">draft</option><option value="validated">validated</option></select></label>
      <button className="rounded-lg bg-gray-950 px-4 py-3 font-bold text-white">검토 내용 저장</button>
    </form>
    {draft?.status==='validated'?<button className="mt-4 rounded-lg border border-red-300 px-4 py-3 text-sm font-bold text-red-700" onClick={()=>mutate({action:'activate_setup',draftId:draft.id})}>paused 프로그램으로 생성</button>:null}
  </section>
}

function UsersView({state,mutate}:{state:State;mutate:(payload:Record<string,unknown>)=>Promise<any>}){return <section className={card}><h2 className="text-xl font-black">실제 베타 사용자 운영</h2><p className="mt-2 text-sm text-gray-600">계정은 비가역 해시 별칭으로만 표시합니다. 이메일·실명·검색어·메시지는 표시하지 않습니다.</p><div className="mt-4 grid gap-3">{state.members.length?state.members.map(member=><article key={member.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_auto]"><div><strong>{member.account_ref}</strong><p className="text-sm text-gray-600">{member.status} · {member.stage} · {new Date(member.enrolled_at).toLocaleString('ko-KR')}</p></div><div className="flex gap-2"><button className="border px-3 py-2 text-sm" onClick={()=>mutate({action:'review_member',memberId:member.id,status:'active',reason:'ADMIN_APPROVED'})}>승인</button><button className="border px-3 py-2 text-sm" onClick={()=>mutate({action:'review_member',memberId:member.id,status:'suspended',reason:'ADMIN_SUSPENDED'})}>정지</button></div></article>):<p>대상 사용자가 없습니다.</p>}</div></section>}

function SchoolsView({state,programId,mutate}:{state:State;programId?:string;mutate:(payload:Record<string,unknown>)=>Promise<any>}){async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!programId)return;const form=new FormData(event.currentTarget);await mutate({action:'create_campaign',programId,schoolId:null,campaignCode:String(form.get('code')),channel:String(form.get('channel')),inviteId:null,nextAction:String(form.get('nextAction')||'')||null})}return <div className="grid gap-6 lg:grid-cols-2"><section className={card}><h2 className="text-xl font-black">첫 학교 운영 보드</h2><p className="mt-2 text-sm text-gray-600">학교 캠페인과 최소 10명 aggregate만 표시하며 사용자 명단과 개인 drill-down은 없습니다.</p><div className="mt-4 space-y-3">{state.campaigns.map(item=><div key={item.id} className="rounded-lg border p-3"><strong>{item.campaign_code}</strong><p className="text-sm">{item.channel} · {item.status} · {item.next_action||'다음 작업 미정'}</p></div>)}</div></section><section className={card}><h2 className="font-bold">안전한 학교 캠페인 준비</h2><form className="mt-4 space-y-3" onSubmit={submit}><input className={input} name="code" placeholder="school_campaign_01" required/><select className={input} name="channel"><option>instagram</option><option>threads</option><option>x</option><option>tiktok</option><option>youtube</option><option>community</option></select><input className={input} name="nextAction" placeholder="다음 콘텐츠 메모"/><button className="w-full bg-gray-950 p-3 text-white">draft 캠페인 생성</button></form></section></div>}

function AdvertisersView({state}:{state:State}){return <section className={card}><h2 className="text-xl font-black">첫 광고주 운영 보드</h2><p className="mt-2 text-sm text-gray-600">신청·검수·견적·manual payment·예약 lifecycle만 표시합니다. 광고 문구와 계정 소유자 정보는 이 보드에 노출하지 않습니다.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div><h3 className="font-bold">요청 {state.advertisers.requests.length}</h3>{state.advertisers.requests.map(item=><p key={item.id} className="mt-2 rounded-lg border p-3 text-sm">{item.status} · {item.requested_placement}</p>)}</div><div><h3 className="font-bold">주문 {state.advertisers.orders.length}</h3>{state.advertisers.orders.map(item=><p key={item.id} className="mt-2 rounded-lg border p-3 text-sm">{item.status} · {item.payment_provider} · {item.total_krw.toLocaleString()}원</p>)}</div></div><p className="mt-4 rounded-lg bg-gray-100 p-3 text-sm">Production 결제는 manual 또는 disabled만 허용하며 PortOne live 활성화는 이 화면에서 지원하지 않습니다.</p></section>}

function TasksView({state,programId,mutate}:{state:State;programId?:string;mutate:(payload:Record<string,unknown>)=>Promise<any>}){async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await mutate({action:'create_task',programId:programId??null,taskType:String(form.get('type')),priority:String(form.get('priority')),summary:String(form.get('summary')),dueAt:null})}return <div className="grid gap-6 lg:grid-cols-2"><section className={card}><h2 className="text-xl font-black">운영 작업 큐</h2>{state.tasks.map(item=><div key={item.id} className="mt-3 rounded-lg border p-3"><strong>{item.priority} · {item.task_type}</strong><p className="text-sm">{item.safe_summary}</p><button className="mt-2 border px-3 py-1 text-sm" onClick={()=>mutate({action:'update_task',taskId:item.id,status:'resolved',priority:item.priority,assignee:'admin:controlled-beta',resolution:'OPERATOR_RESOLVED'})}>해결</button></div>)}</section><section className={card}><h2 className="font-bold">작업 추가</h2><form className="mt-3 space-y-3" onSubmit={create}><select className={input} name="type"><option value="feedback">feedback</option><option value="health_warning">health warning</option><option value="onboarding_failure">onboarding failure</option><option value="advertiser_review">advertiser review</option><option value="cron_failure">cron failure</option></select><select className={input} name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select><input className={input} name="summary" maxLength={300} required placeholder="개인정보 없는 안전한 작업 요약"/><button className="w-full bg-gray-950 p-3 text-white">작업 생성</button></form><h2 className="mt-6 font-bold">사용자 피드백 {state.feedback.length}</h2>{state.feedback.slice(0,20).map(item=><div key={item.id} className="mt-2 rounded-lg bg-gray-50 p-3 text-sm"><strong>{item.priority} · {item.kind}</strong><p>{item.description}</p><p className="text-gray-500">{item.page_path} · {item.status}</p></div>)}</section></div>}

function ReadinessView({state,programId,mutate}:{state:State;programId?:string;mutate:(payload:Record<string,unknown>)=>Promise<any>}){return <div className="grid gap-6 lg:grid-cols-2"><section className={card}><h2 className="text-xl font-black">베타 중단 조건</h2><p className="mt-2 text-sm text-gray-600">조치는 기능을 닫고 audit을 남길 뿐 사용자를 자동 연락하거나 데이터를 삭제하지 않습니다.</p><div className="mt-4 grid gap-2">{['people_search','messaging','promotion_application','promotion_operations','invites','all'].map(scope=><button key={scope} className="rounded-lg border border-red-200 p-3 text-left text-sm text-red-700" onClick={()=>mutate({action:'stop',scope,reason:'OPERATOR_EMERGENCY_STOP'})}>{scope} 중단</button>)}</div></section><section className={card}><h2 className="text-xl font-black">졸업 준비도 판정</h2><p className="mt-2 text-sm">launch_candidate는 자동 공개가 아니라 운영자 판단 기록입니다.</p><div className="mt-4 space-y-2">{state.readiness.map(item=><p key={item.id} className="rounded-lg border p-3 text-sm">{item.status} · blocker {item.blocker_codes.length}개</p>)}</div>{programId?<button className="mt-4 w-full bg-gray-950 p-3 text-white" onClick={()=>mutate({action:'record_readiness',programId,status:'limited_beta',criteria:{health:true,rls:true,live_payment:false},blockerCodes:[],operatorDecision:true})}>limited_beta 검토 기록</button>:null}</section></div>}

function ReportView({state}:{state:State}){return <section className={card}><h2 className="text-xl font-black">제한 베타 일일 보고</h2><p className="mt-2 text-sm text-gray-600">일일·최근 7일 비교는 aggregate만 사용하며 작은 세그먼트는 마스킹합니다.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['programs',state.programs.length],['members',state.members.length],['open tasks',state.tasks.filter(item=>!['resolved','dismissed'].includes(item.status)).length],['incidents',state.incidents.length]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-gray-50 p-4"><p className="text-sm text-gray-500">{label}</p><strong className="text-2xl">{value}</strong></div>)}</div><div className="mt-5 flex gap-3"><a className="border px-4 py-3" href="/api/admin/beta/report?format=json">JSON</a><a className="border px-4 py-3" href="/api/admin/beta/report?format=csv">CSV</a></div></section>}
