'use client'
import { useState } from 'react'
import { supabase } from '@/lib/supabase'
interface Props { profileId: string; nickname: string; instagramId: string | null; onClose: () => void }
export default function EditDeleteModal({ profileId, nickname, instagramId, onClose }: Props) {
  const [mode, setMode] = useState<'select' | 'edit' | 'delete'>('select')
  const [newInstagram, setNewInstagram] = useState('')
  const [selfClaimed, setSelfClaimed] = useState(false)
  const [loading, setLoading] = useState(false)
  const [done, setDone] = useState(false)
  const submit = async () => {
    if (!selfClaimed) return alert('Please confirm you are authorized.')
    setLoading(true)
    await supabase.from('reports').insert({ profile_id: profileId, type: mode, reason: mode === 'delete' ? 'Delete request' : 'Edit request', requested_instagram_id: mode === 'edit' ? newInstagram : null, is_self_claimed: true, status: 'pending' })
    setLoading(false); setDone(true)
  }
  if (done) return (<div className='fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4'><div className='bg-white rounded-2xl p-6 w-full max-w-sm text-center'><div className='text-4xl mb-3'>OK</div><p className='font-semibold mb-4'>Request submitted</p><button onClick={onClose} className='w-full bg-blue-600 text-white py-2 rounded-lg'>Close</button></div></div>)
  return (<div className='fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4'><div className='bg-white rounded-2xl p-6 w-full max-w-sm'><h3 className='font-bold text-lg mb-4'>{nickname}</h3>{mode === 'select' && (<div className='space-y-3'><button onClick={() => setMode('edit')} className='w-full border border-gray-200 rounded-xl p-3 text-left hover:bg-gray-50'><div className='font-medium'>Edit Instagram ID</div></button><button onClick={() => setMode('delete')} className='w-full border border-red-100 rounded-xl p-3 text-left hover:bg-red-50'><div className='font-medium text-red-600'>Request deletion</div></button><button onClick={onClose} className='w-full text-gray-500 py-2 text-sm'>Cancel</button></div>)}{mode === 'edit' && (<div className='space-y-3'><p className='text-sm text-gray-600'>Current: {instagramId ? '@' + instagramId : 'None'}</p><input value={newInstagram} onChange={e => setNewInstagram(e.target.value.replace('@', ''))} placeholder='New Instagram ID' className='w-full border border-gray-200 rounded-lg px-3 py-2 text-sm' /><label className='flex items-start gap-2 text-sm text-gray-600 cursor-pointer'><input type='checkbox' checked={selfClaimed} onChange={e => setSelfClaimed(e.target.checked)} className='mt-0.5' />I am authorized to make this request</label><button onClick={submit} disabled={loading || !newInstagram} className='w-full bg-blue-600 text-white py-2 rounded-lg disabled:opacity-50'>{loading ? 'Processing...' : 'Submit edit'}</button><button onClick={() => setMode('select')} className='w-full text-gray-500 py-2 text-sm'>Back</button></div>)}{mode === 'delete' && (<div className='space-y-3'><p className='text-sm text-gray-600'>Request deletion of this profile. Admin will review.</p><label className='flex items-start gap-2 text-sm text-gray-600 cursor-pointer'><input type='checkbox' checked={selfClaimed} onChange={e => setSelfClaimed(e.target.checked)} className='mt-0.5' />I am authorized to make this request</label><button onClick={submit} disabled={loading} className='w-full bg-red-600 text-white py-2 rounded-lg disabled:opacity-50'>{loading ? 'Processing...' : 'Request deletion'}</button><button onClick={() => setMode('select')} className='w-full text-gray-500 py-2 text-sm'>Back</button></div>)}</div></div>)
}