'use client'

import { FormEvent, useEffect, useState } from 'react'

type Program={id:string;name:string}
type Feedback={id:string;kind:string;description:string;page_path:string;status:string;created_at:string}
const input='w-full rounded-lg border border-gray-300 px-3 py-2'

export default function FeedbackClient({programs}:{programs:Program[]}){
  const [items,setItems]=useState<Feedback[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('')
  async function load(){const response=await fetch('/api/beta/feedback',{cache:'no-store'});if(response.ok)setItems((await response.json()).feedback??[])}
  useEffect(()=>{load().catch(()=>undefined)},[])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setNotice('');const form=new FormData(event.currentTarget);const response=await fetch('/api/beta/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({programId:String(form.get('programId')),kind:String(form.get('kind')),description:String(form.get('description')),pagePath:String(form.get('pagePath')),coarseBrowser:String(form.get('browser')),coarseDevice:String(form.get('device'))})});if(!response.ok){const body=await response.json().catch(()=>({}));setError(body.error==='INVALID_FEEDBACK'?'개인 연락처·외부 ID·URL 없이 현상만 적어주세요.':'피드백을 제출할 수 없습니다. 활성 베타 권한을 확인해주세요.');return}setNotice('피드백을 안전하게 접수했습니다.');event.currentTarget.reset();await load()}
  return <div className="space-y-6"><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">운영팀에 피드백 보내기</h2><p className="mt-2 text-sm text-gray-600">다른 사람의 이름·이메일·Instagram·검색어·메시지·전화번호·URL은 적지 마세요. 화면 HTML, 토큰, 쿠키는 자동 첨부되지 않습니다.</p>{notice?<p role="status" className="mt-3 bg-green-50 p-3">{notice}</p>:null}{error?<p role="alert" className="mt-3 bg-red-50 p-3">{error}</p>:null}<form className="mt-4 space-y-3" onSubmit={submit}><select className={input} name="programId" required>{programs.map(program=><option key={program.id} value={program.id}>{program.name}</option>)}</select><select className={input} name="kind"><option value="error">오류</option><option value="confusing">이해하기 어려움</option><option value="missing_feature">찾기 어려운 기능</option><option value="greeting_message">안부·메시지</option><option value="privacy">개인정보 우려</option><option value="advertising">광고</option><option value="other">기타</option></select><input className={input} name="pagePath" defaultValue="/account" pattern="/[A-Za-z0-9_/-]*" required/><textarea className={input} name="description" minLength={3} maxLength={2000} rows={6} required placeholder="개인 식별정보 없이 문제 상황과 기대 동작을 적어주세요."/><div className="grid gap-3 sm:grid-cols-2"><select className={input} name="browser"><option>chrome</option><option>safari</option><option>edge</option><option>firefox</option><option>other</option></select><select className={input} name="device"><option>mobile</option><option>tablet</option><option>desktop</option><option>other</option></select></div><button className="w-full rounded-lg bg-gray-950 p-3 font-bold text-white">피드백 제출</button></form></section><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">내 제출 내역</h2>{items.map(item=><article key={item.id} className="mt-3 rounded-lg border p-3 text-sm"><strong>{item.kind} · {item.status}</strong><p className="mt-1">{item.description}</p><p className="mt-1 text-gray-500">{item.page_path} · {new Date(item.created_at).toLocaleString('ko-KR')}</p></article>)}</section></div>
}
