import { readFileSync } from 'node:fs';import { join } from 'node:path';import { describe,expect,it } from 'vitest'
const sql=readFileSync(join(process.cwd(),'supabase/migrations/20260729190000_controlled_beta_operations.sql'),'utf8')
const tables=['beta_setup_drafts','beta_program_setup_snapshots','beta_operator_notes','beta_feedback','beta_operation_tasks','beta_campaigns','beta_campaign_aggregates','beta_readiness_snapshots']
describe('PHASE 10I migration',()=>{
  it('creates eight RLS and FORCE RLS operation tables',()=>{for(const table of tables){expect(sql).toContain(`CREATE TABLE public.${table}`);expect(sql).toContain(`'${table}'`)}expect(sql).toContain('ENABLE ROW LEVEL SECURITY');expect(sql).toContain('FORCE ROW LEVEL SECURITY')})
  it('grants no anon tables and only owner feedback to authenticated',()=>{expect(sql).toContain('REVOKE ALL ON TABLE');expect(sql).toContain('GRANT SELECT,INSERT ON public.beta_feedback TO authenticated');expect(sql).toContain('beta_feedback_owner_select');expect(sql).toContain('beta_feedback_owner_insert');expect(sql).not.toMatch(/GRANT ALL ON TABLE[^;]+authenticated/)})
  it('keeps exact small aggregate counts out of storage',()=>{expect(sql).toContain('(masked AND metric_count IS NULL)');expect(sql).toContain('(NOT masked AND metric_count >= 10)')})
  it('makes every privileged function security definer with fixed search path',()=>{for(const name of ['admin_save_beta_setup','admin_activate_beta_setup','admin_issue_beta_invite','admin_review_beta_member','admin_set_beta_feature','redeem_beta_invite','has_beta_feature_access','admin_update_beta_task','admin_controlled_beta_stop','admin_create_beta_task','admin_create_beta_note','admin_create_beta_campaign','admin_record_beta_readiness','has_active_beta_program_membership'])expect(sql).toContain(`FUNCTION public.${name}`);expect(sql.match(/SECURITY DEFINER SET search_path=''/g)?.length).toBeGreaterThanOrEqual(14);expect(sql).toContain('FROM PUBLIC,anon,authenticated');expect(sql).toContain('TO service_role');expect(sql).toContain('actor_user_id=auth.uid()')})
  it('updates draft keys and rejects explicit draft or program key conflicts',()=>{expect(sql).toContain('SET draft_key=requested_draft_key');expect(sql).toContain("RAISE EXCEPTION 'DRAFT_KEY_CONFLICT'");expect(sql).toContain("RAISE EXCEPTION 'PROGRAM_KEY_CONFLICT'")})
  it('requires the three fail-closed stop conditions in app-facing SQL',()=>{expect(sql).toContain('{"PRIVACY_EXPOSURE":true,"RLS_FAILURE":true,"HEALTH_FAILURE":true}');expect(sql).toContain("RAISE EXCEPTION 'REQUIRED_STOP_CONDITION_MISSING'")})
  it('copies an immutable setup snapshot during paused idempotent activation',()=>{expect(sql).toContain('CREATE TABLE public.beta_program_setup_snapshots');expect(sql).toContain('PROGRAM_SETUP_SNAPSHOT_IMMUTABLE');expect(sql).toContain("VALUES(draft.draft_key,draft.name,'paused',true");expect(sql).toContain('IF draft.status=\'activated\'');expect(sql).toContain('draft.max_users,draft.target_scope,draft.enabled_features,draft.invite_policy,draft.approval_waitlist_enabled,draft.stop_conditions');const activation=sql.slice(sql.indexOf('admin_activate_beta_setup'),sql.indexOf('-- A PHASE 10I program contract'));expect(activation).not.toContain('beta_invites');expect(activation).not.toContain('beta_feature_flags')})
  it('enforces snapshot invite, feature and capacity contracts at DB boundaries',()=>{expect(sql).toContain('INVITE_MAX_USES_EXCEEDS_SETUP');expect(sql).toContain('INVITE_EXPIRY_EXCEEDS_SETUP');expect(sql).toContain('FEATURE_NOT_IN_SETUP');expect(sql).toContain('PROGRAM_FULL');expect(sql).toContain("requested_feature=ANY(snapshot.enabled_features)")})
})
