import {chromium,expect} from '@playwright/test'
import {mkdir,writeFile} from 'node:fs/promises'
import {setup} from '../growth-ux/browser.mjs'
const folder='.local/game-visual-polish/motion'
await mkdir(folder,{recursive:true})
const browser=await chromium.launch({channel:'chrome',headless:true})
const results=[]
try {
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'no-preference'})
 const evidence=await setup(page)
 // Explicit synthetic document visibility signal; real viewport observer below.
 await page.addInitScript(()=>Object.defineProperty(document,'hidden',{configurable:true,get:()=>window.__motionHidden??false}))
 await page.goto('http://127.0.0.1:3117/')
 const scene=page.locator('.sl-hero-world .sl-world'),image=scene.locator('.sl-world-image'),button=scene.getByRole('button')
 await scene.scrollIntoViewIfNeeded()
 await expect(scene).toHaveAttribute('data-motion','running')
 await expect(image).toHaveCSS('animation-play-state','running')
 await button.focus();await page.keyboard.press('Space')
 await expect(scene).toHaveAttribute('data-motion','paused')
 await expect(button).toHaveAttribute('aria-pressed','true')
 await expect(image).toHaveCSS('animation-play-state','paused')
 const still=await image.evaluate(e=>getComputedStyle(e).transform)
 await page.waitForTimeout(180)
 expect(await image.evaluate(e=>getComputedStyle(e).transform)).toBe(still)
 const box=await button.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44);expect(box.width).toBeGreaterThanOrEqual(44)
 expect(await button.evaluate(e=>!!e.closest('[aria-hidden=true]'))).toBe(false)
 await page.screenshot({path:`${folder}/pause-390.png`})
 await page.keyboard.press('Enter');await expect(scene).toHaveAttribute('data-motion','running')
 await page.evaluate(()=>{window.__motionHidden=true;document.dispatchEvent(new Event('visibilitychange'))})
 await expect(scene).toHaveAttribute('data-motion','paused')
 await page.evaluate(()=>{window.__motionHidden=false;document.dispatchEvent(new Event('visibilitychange'))})
 await expect(scene).toHaveAttribute('data-motion','running')
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight))
 await expect(scene).toHaveAttribute('data-motion','paused')
 await scene.scrollIntoViewIfNeeded();await expect(scene).toHaveAttribute('data-motion','running')
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(scene).toHaveAttribute('data-motion','paused');await expect(button).toBeDisabled()
 await expect(image).toHaveCSS('animation-name','none')
 await page.emulateMedia({reducedMotion:'no-preference'})
 await expect(button).toBeEnabled();await expect(scene).toHaveAttribute('data-motion','paused')
 await button.click();await expect(scene).toHaveAttribute('data-motion','running')
 results.push({check:'keyboard pause/resume, still transform, 44px, outside aria-hidden, real offscreen, OS preference changes',pass:true,button:box,hiddenTest:'synthetic document.hidden getter and visibilitychange event'})
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await scene.scrollIntoViewIfNeeded()
 await expect(scene).toHaveAttribute('data-motion','paused');await expect(button).toBeDisabled()
 expect(evidence.calls.filter(x=>x.method!=='GET')).toHaveLength(0);expect(evidence.errors).toEqual([])
 results.push({check:'reduced-motion on initial load',pass:true,writes:0})
 await page.close()
 const videoContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'no-preference',recordVideo:{dir:folder,size:{width:390,height:844}}})
 const videoPage=await videoContext.newPage();await setup(videoPage)
 await videoPage.goto('http://127.0.0.1:3117/school/example-school?level=10')
 const videoScene=videoPage.locator('.sl-hub-world .sl-world');await videoScene.scrollIntoViewIfNeeded()
 await expect(videoScene).toHaveAttribute('data-motion','running')
 await videoPage.waitForTimeout(8000)
 await videoScene.getByRole('button').click();await videoPage.waitForTimeout(2000)
 const videoPath=await videoPage.video().path();await videoContext.close()
 results.push({check:'actual React browser video; 8s motion + 2s pause after load',path:videoPath,fixture:'local synthetic, not live Preview'})
} finally {await browser.close();await writeFile(`${folder}/results.json`,JSON.stringify(results,null,2))}
console.log(JSON.stringify(results))
